{
 "title": "Base",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "DASHBOARD BASE ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 1 },
   "options": {
    "content": "<a href=\"/d/df0xjchqcxfcwa/principal\"\n   style=\"\n      display:inline-block;\n      padding:10px 20px;\n      background-color:#1f78c1;\n      color:white;\n      text-decoration:none;\n      border-radius:5px;\n      font-size:12px;\n      text-align:rigth;\n   \">\n   ◀ ver NCE\n</a>"
   },
   "targets": [
    {
     "dataset": "dashboard",
     "rawSql": "SELECT NOW() AS Ultima_Atualizacao;"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "dashboard",
     "rawSql": "SELECT NOW() AS Ultima_Atualizacao;"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 1 },
   "options": {
    "content": "<a href=\"/d/bfeeqw26p2z9cd/arquivados\"\n   style=\"\n      display:inline-block;\n      padding:10px 20px;\n      background-color:#1f78c1;\n      color:white;\n      text-decoration:none;\n      border-radius:5px;\n      font-size:12px;\n      text-align:center;\n   \">\n    ▶ Arquivados\n</a>"
   },
   "targets": [
    {
     "dataset": "dashboard",
     "rawSql": "SELECT NOW() AS Ultima_Atualizacao;"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "BASE",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "dashboard",
     "rawSql": "SELECT COUNT(*) AS total_processos\r\nFROM base;\r\n  "
    }
   ]
  },
  {
   "title": "Normal",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "dashboard",
     "rawSql": "SELECT COUNT(*) AS total_processos\r\nFROM base\r\nWHERE incidente LIKE 'N%';\r\n  "
    }
   ]
  },
  {
   "title": "NCE - N",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 7, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "dashboard",
     "rawSql": "SELECT COUNT(*) AS total_processos\r\nFROM base\r\nWHERE incidente LIKE 'N%'\r\n  AND sigla = 'NCE';"
    }
   ]
  },
  {
   "title": "Middle - N",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 9, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "dashboard",
     "rawSql": "SELECT COUNT(*) AS total_processos\r\nFROM base\r\nWHERE incidente LIKE 'N%'\r\n  AND sigla = 'MIDDLE';"
    }
   ]
  },
  {
   "title": "Tomb 1 - N",
   "type": "stat",
   "description": "VERIFICANDO ...",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "dashboard",
     "rawSql": "SELECT COUNT(*) AS total_processos\r\nFROM base\r\nWHERE incidente LIKE 'N%'\r\n  AND sigla = 'TOMB';"
    }
   ]
  },
  {
   "title": "Tomb 2 - N",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "dashboard",
     "rawSql": "SELECT COUNT(*) AS total_processos\r\nFROM base\r\nWHERE incidente LIKE 'N%'\r\n  AND sigla = 'TOMB2';"
    }
   ]
  },
  {
   "title": "AJUST N",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 17, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "dashboard",
     "rawSql": "SELECT COUNT(*) AS total_processos\r\nFROM base\r\nWHERE incidente LIKE 'N%'\r\n  AND sigla = 'AJUST';"
    }
   ]
  },
  {
   "title": "Sem Sigla N",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 20, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "dashboard",
     "rawSql": "SELECT COUNT(*) AS total_processos\r\nFROM base\r\nWHERE incidente LIKE 'N%'\r\n  AND sigla = 'sem sigla';"
    }
   ]
  },
  {
   "title": "Morto",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "dashboard",
     "rawSql": "SELECT COUNT(*) AS total_processos\r\nFROM base\r\nWHERE incidente LIKE 'M%';\r\n  "
    }
   ]
  },
  {
   "title": "NCE - M",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 7, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "dashboard",
     "rawSql": "SELECT COUNT(*) AS total_processos\r\nFROM base\r\nWHERE incidente LIKE 'M%'\r\n  AND sigla = 'NCE';"
    }
   ]
  },
  {
   "title": "Middle - M",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 9, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "dashboard",
     "rawSql": "SELECT COUNT(*) AS total_processos\r\nFROM base\r\nWHERE incidente LIKE 'M%'\r\n  AND sigla = 'MIDDLE';"
    }
   ]
  },
  {
   "title": "Tomb 1 - M",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "dashboard",
     "rawSql": "SELECT COUNT(*) AS total_processos\r\nFROM base\r\nWHERE incidente LIKE 'M%'\r\n  AND sigla = 'TOMB';"
    }
   ]
  },
  {
   "title": "Tomb 2 - M",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "dashboard",
     "rawSql": "SELECT COUNT(*) AS total_processos\r\nFROM base\r\nWHERE incidente LIKE 'M%'\r\n  AND sigla = 'TOMB2';"
    }
   ]
  },
  {
   "title": "AJUST M",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 17, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "dashboard",
     "rawSql": "SELECT COUNT(*) AS total_processos\r\nFROM base\r\nWHERE incidente LIKE 'M%'\r\n  AND sigla = 'AJUST';"
    }
   ]
  },
  {
   "title": "Sem Sigla M",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 20, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "dashboard",
     "rawSql": "SELECT COUNT(*) AS total_processos\r\nFROM base\r\nWHERE incidente LIKE 'M%'\r\n  AND sigla = 'sem sigla';"
    }
   ]
  }
 ]
}